[package]
name = "streampay"
version = "0.1.0"
edition = "2019"

[dependencies]
solana-program = "1.3.6"
thiserror = "1.0"
byteorder = "1.4"

[dev-dependencies]
solana-program-test = "1.3.6"
tokio = { version = "1", features = ["full"] }

[[bin]]
name = "streampay"
path = "src/streampay.rs"
